const d1WrestlingSchools = [
    "Air Force Academy",
    "American University",
    "Appalachian State University",
    "Arizona State University",
    "Binghamton University",
    "Bloomsburg University of Pennsylvania",
    "Boise State University",
    "Boston University",
    "Brown University",
    "Bucknell University",
    "California Polytechnic State University",
    "Campbell University",
    "Central Michigan University",
    "The Citadel",
    "Clarion University of Pennsylvania",
    "Cleveland State University",
    "Columbia University",
    "Cornell University",
    "Davidson College",
    "Drexel University",
    "Duke University",
    "East Tennessee State University",
    "Eastern Michigan University",
    "Edinboro University of Pennsylvania",
    "Fairleigh Dickinson University",
    "George Mason University",
    "George Washington University",
    "Harvard University",
    "Hofstra University",
    "University of Illinois at Urbana-Champaign",
    "Indiana University Bloomington",
    "University of Iowa",
    "Iowa State University",
    "University of Maryland, College Park",
    "University of Michigan",
    "Michigan State University",
    "University of Minnesota",
    "Missouri University of Science and Technology",
    "University of Missouri",
    "North Carolina State University",
    "University of North Carolina at Chapel Hill",
    "North Dakota State University",
    "Northern Colorado",
    "Northern Illinois University",
    "Northwestern University",
    "The Ohio State University",
    "Old Dominion University",
    "University of Oklahoma",
    "Oklahoma State University",
    "Oregon State University",
    "University of Pennsylvania",
    "Pennsylvania State University",
    "Princeton University",
    "Purdue University",
    "Rider University",
    "Rutgers, The State University of New Jersey",
    "Sacred Heart University",
    "University of South Dakota",
    "South Dakota State University",
    "Southern Illinois University Edwardsville",
    "Stanford University",
    "University at Buffalo, The State University of New York",
    "University of Tennessee at Chattanooga",
    "University of Tennessee at Martin",
    "Utah Valley University",
    "Virginia Military Institute",
    "Virginia Tech",
    "VMI Military Institute",
    "VMI Military Institute",
    "West Virginia University",
    "University of Wisconsin-Madison",
    "University of Wisconsin-Milwaukee",
    "Wyoming"
];

console.log(d1WrestlingSchools);
